---
# task to configure backend servers
- name: Installing httpd and php
  package:
          name:
               - httpd
               - php
          state: present

- name: Copying php file to check IP
  copy:
          src:  "/var/www/html/ip.php"
          dest: "/var/www/html/ipcheck.php"

- name: Copying webpages
  copy:
          src:  "/var/www/html/"
          dest: "/var/www/html/"

- name: Starting the httpd service
  service:
          name: "httpd"
          state: started
